{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: app
        image: {{ .Values.image | default "budgetkey/budgetkey-app:latest" | quote }}
        ports:
        - containerPort: 4000
        resources: {{ .Values.resources }}
{{ end }}
