apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-list-manager
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: list-manager
  updatePolicy:
    updateMode: "Off"
