{{ if and .Values.enabled .Values.secretName }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-backup
spec:
  selector:
    matchLabels:
      app: db-backup
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-backup
    spec:
      {{ if .Values.createClusterRole }}
      serviceAccountName: db-backup
      {{ end }}
      containers:
      - name: db-backup
        image: {{ .Values.image | default "orihoch/kubernetes-db-to-s3" | quote }}
        resources: {{ .Values.resources }}
        envFrom:
        - secretRef:
            name: {{ .Values.secretName | quote }}
{{ end }}
