apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-db-backup
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: db-backup
  updatePolicy:
    updateMode: "Off"
