{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
data:
  # DATABASE_URL: postgresql://*********@budgetkey-postgres/private'
  EXTERNAL_ADDRESS: next.obudget.org
  # GOOGLE_KEY: *********.apps.googleusercontent.com
  # GOOGLE_SECRET: *********
  GUNICORN_PORT: "8000"
  # PRIVATE_KEY:
  # PUBLIC_KEY:
{{ end }}
