language: bash
sudo: required
services:
- docker
install:
- curl -L https://raw.githubusercontent.com/hasadna/hasadna-k8s/master/apps_travis_script.sh
  | bash /dev/stdin install_helm
script:
- bash helm_lint_all.sh
deploy:
  provider: script
  script: bash .travis_deploy.sh
  on:
    branch: master
env:
  global:
  - secure: oN4fhXhss/goCbd2RvKqPM+NzMpF0IfmjCIamI7JmOzXo9ObWNEJuh/rTZfH/PUocWGOFs2r90MGc4Xs9WQPxHbJ7xxQeXmeQEu7DKFbruvENgjw0OHK+fzanFkp5WmuMgLXKDSG3HZpKpp7CVDHBoikYeYi5jt7BZvjasPQU+IFM7Sh7UKS/Dq4GTlefvjDuMEKFz8NVoemQpKoNeYnz8c8tNqJZrwfLcgJYfw/uBNGvae18ktHxSzix12L2ZEHjcLRTomef5iaLHoEEqjDHUW+dCOWUfWRys9TDDWqUFSulTj4qA3lpt7AnwMBGhLkLGa0oew8636Z+87iiBC0WUPpjp+vbARrHqJUjvP7ax78CegJO9TfJRsyRP6jreIiDCORP6rb1AiG2giv7i5lCzPWxQJ0DR1XjQY5CV7g/zpbv1tCDnjrEG+kJf7s7D/jCnokCuL4PceUh/YGuSdKJFLKzhx9GDOZlcHycZKclDt7BP/VWIlF9eQeE08/TpPuxYwQdM7sU2EBubt3D4eqYf8iSidSYaCd1vziEb0G+4fNl/FmcVwpwXg94Peaxk/Rh98c9WwTkA/1p1PViDMslEvhhVB+pMJbPRUKlqTWfGjXuSxC+jWtkQ7fjPMGs0A2ADyOKfgIhIv7AGfsjS0HqPTJOfq3rSDoErhdej+uQ+4=
  - secure: XqLRJxmrkrJT/IMDg35xhkydYdXVH42VCiV7alLRCsylxSkMIS51Vzqv3kvALnMdjGTYaWqI4aCcES1JM+FzfYqojilqmuWll7AWzPV1bMgzxTsdlHn2DhroXifgBt0IM/sMAV3HyTP081JWu+iHVWzzIEuy21YhYabOfm5molVLRHojVmQbdY2DkQwx61eLWQzdgaNBP/+5VZCv2a4+vf7SXbgiWSHKjmGh+KKpkB7CSzifdwVFiHT9seCwJS7LmSUghtLwro7a3FJ9ziZHeUqN5U/KP42NaIZ52Lb9eVYJYOj2Urf5ygwbjv2E68yoxpd52XmvrMf51Rp60+vWOHKtrxuSMpxKi5yCTIZAcvCXvOOW3NqvpF33nP+5t1bhCsWOEpjm4hG4G5J3UwWbWesuOmXJ1xln4xNDqxqMRWukmfaqdT3dayk5yJSoXK3YyQRNzwKQ6ffp+CM3PAcLlImm7QAxuDQVVvZOrxzy8uSeLel+BhP3+/+mBH8+SkYpIUj7QwmvyES0sXub8QYWFLRnS+akgBqR3j2TjWfZBlUO4SuEbD2bWqas9qfm9AlZBSE9emLYJ1/Z/sJKlrIRyd9M1xZ7q0q2JgGFSCB2Go75vqi9RZFKbaorUTxgZYlFwI/niGgmkZXCtLGZy0iR3iDhysBjDoBM+7cKBqNBJLY=
