language: bash
sudo: required
services:
- docker
deploy:
  provider: script
  script: bash .travis_deploy.sh
  on:
    branch: master
    condition: "! echo $TRAVIS_COMMIT_MESSAGE | grep -- --no-deploy"
