version: "v0.0.0"
apiVersion: v2
name: budgetkey

dependencies:
- name: app-about
  version: v0.0.0
  repository: file://charts-external/app-about
- name: app-dashboards
  version: v0.0.0
  repository: file://charts-external/app-dashboards
- name: app-generic-item
  version: v0.0.0
  repository: file://charts-external/app-generic-item
- name: app-main-page
  version: v0.0.0
  repository: file://charts-external/app-main-page
- name: app-source-of-money
  version: v0.0.0
  repository: file://charts-external/app-source-of-money
- name: app-profile
  version: v0.0.0
  repository: file://charts-external/app-profile
- name: app-search
  version: v0.0.0
  repository: file://charts-external/app-search
- name: auth
  version: v0.0.0
  repository: file://charts-external/auth
- name: data-api
  version: v0.0.0
  repository: file://charts-external/data-api
- name: data-input
  version: v0.0.0
  repository: file://charts-external/data-input
- name: dgp-server
  version: v0.0.0
  repository: file://charts-external/dgp-server
- name: dgp-ui
  version: v0.0.0
  repository: file://charts-external/dgp-ui
- name: elasticsearch-new
  version: v0.0.0
  repository: file://charts-external/elasticsearch-new
- name: emails
  version: v0.0.0
  repository: file://charts-external/emails
- name: kibana
  version: v0.0.0
  repository: file://charts-external/kibana
- name: list-manager
  version: v0.0.0
  repository: file://charts-external/list-manager
- name: nginx
  version: v0.0.0
  repository: file://charts-external/nginx
- name: openprocure
  version: v0.0.0
  repository: file://charts-external/openprocure
- name: pipelines
  version: v0.0.0
  repository: file://charts-external/pipelines
- name: postgres
  version: v0.0.0
  repository: file://charts-external/postgres
- name: search-api
  version: v0.0.0
  repository: file://charts-external/search-api
- name: search-api-new
  version: v0.0.0
  repository: file://charts-external/search-api-new
- name: socialmap
  version: v0.0.0
  repository: file://charts-external/socialmap
- name: themes
  version: v0.0.0
  repository: file://charts-external/themes
