version: "v0.0.0"
apiVersion: v2
name: budgetkey

dependencies:
- name: app
  version: v0.0.0
  repository: file://charts-external/app
- name: api
  version: v0.0.0
  repository: file://charts-external/api
- name: app-source-of-money
  version: v0.0.0
  repository: file://charts-external/app-source-of-money
- name: data-input
  version: v0.0.0
  repository: file://charts-external/data-input
- name: dgp-server
  version: v0.0.0
  repository: file://charts-external/dgp-server
- name: dgp-ui
  version: v0.0.0
  repository: file://charts-external/dgp-ui
- name: elasticsearch8
  version: v0.0.0
  repository: file://charts-external/elasticsearch8
- name: elasticsearch-new
  version: v0.0.0
  repository: file://charts-external/elasticsearch-new
- name: emails
  version: v0.0.0
  repository: file://charts-external/emails
- name: kibana
  version: v0.0.0
  repository: file://charts-external/kibana
# - name: list-manager
#   version: v0.0.0
#   repository: file://charts-external/list-manager
- name: nginx
  version: v0.0.0
  repository: file://charts-external/nginx
- name: openprocure
  version: v0.0.0
  repository: file://charts-external/openprocure
- name: pipelines
  version: v0.0.0
  repository: file://charts-external/pipelines
- name: postgres
  version: v0.0.0
  repository: file://charts-external/postgres
- name: socialmap
  version: v0.0.0
  repository: file://charts-external/socialmap
- name: themes
  version: v0.0.0
  repository: file://charts-external/themes
