{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch8
spec:
  selector:
    matchLabels:
      app: elasticsearch8
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch8
    spec:
      containers:
      - name: es01
        image: "docker.elastic.co/elasticsearch/elasticsearch:{{ .Values.stackVersion | default "8.17.0" | quote }}"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {{ .Values.resources }}
        env:
        - name: ES_JAVA_OPTS
          value: {{ .Values.ES_JAVA_OPTS | quote }}
        - name: node.name
          value: es01
        - name: cluster.name
          value: budgetkey-es-cluster
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ELASTIC_PASSWORD
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: ELASTIC_PASSWORD}}
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.http.ssl.enabled
          value: "true"
        - name: xpack.security.http.ssl.key
          value: config/certs/es01/es01.key
        - name: xpack.security.http.ssl.certificate
          value: config/certs/es01/es01.crt
        - name: xpack.security.http.ssl.certificate_authorities
          value: config/certs/ca/ca.crt
        - name: xpack.security.transport.ssl.enabled
          value: "true"
        - name: xpack.security.transport.ssl.key
          value: config/certs/es01/es01.key
        - name: xpack.security.transport.ssl.certificate
          value: config/certs/es01/es01.crt
        - name: xpack.security.transport.ssl.certificate_authorities
          value: config/certs/ca/ca.crt
        - name: xpack.security.transport.ssl.verification_mode
          value: certificate
        - name: xpack.license.self_generated.type
          value: basic
        volumeMounts:
        - name: certs
          mountPath: /usr/share/elasticsearch/config/certs
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: esdata
        nfs:
          server: {{ .Values.nfsServer | quote }}
          path: {{ .Values.nfsPathEsData | quote }}
      - name: certs
        nfs:
          server: {{ .Values.nfsServer | quote }}
          path: {{ .Values.nfsPathEsCerts | quote }}
{{ end }}
