apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-elasticsearch8
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: elasticsearch8
  updatePolicy:
    updateMode: "Off"
