{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
      - name: search-api
        image: {{ .Values.image | default "budgetkey/open-budget-search-api:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {"requests": {"cpu": "50m", "memory": "100Mi"}, "limits": {"cpu": "100m", "memory": "200Mi"}}
        env:
        - name: DB_DB
          value: {{ .Values.DB_DB | default "obudget" | quote }}
        - name: DB_HOST
          value: {{ .Values.DB_HOST | default "postgres" | quote }}
        - name: DB_PORT
          value: {{ .Values.DB_PORT | default "5432" | quote }}
        - name: ES_HOST
          value: elasticsearch
        - name: ES_PORT
          value: "9200"
        - name: INDEX_NAME
          value: {{ .Values.INDEX_NAME | default "budgetkey_20180319232948938759_e07786a8" | quote }}
        {{ if .Values.secretName }}
        - name: DB_PWD
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DB_PWD}}
        - name: DB_USER
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DB_USER}}
        {{ else }}
        - name: DB_PWD
          value: "123456"
        - name: DB_USER
          value: budgetkey
        {{ end }}
{{ end }}
