{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  16;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
        worker_connections  4096;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main_ext  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        '"$host" sn="$server_name" '
                        'rt=$request_time '
                        'ua="$upstream_addr" us="$upstream_status" '
                        'ut="$upstream_response_time" ul="$upstream_response_length" '
                        'cs=$upstream_cache_status' ;

        access_log  /var/log/nginx/access.log main_ext;

        proxy_cache_path /var/run/ levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout           65;
        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;

        gzip  on;

        upstream api-server {
            server api:5000;
            keepalive 32;
        }

        upstream slow-api-server {
            server api:5001;
            keepalive 32;
        }

        server {
            listen 80 default_server;
            include /etc/nginx/default_server.conf;
            error_page 500 502 503 504 /500.html;
            location = /500.html {
                root /usr/share/nginx/errors;
                internal;
            }
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            include "/etc/nginx/server-rules.conf";

            location / {
              proxy_http_version 1.1;
              proxy_set_header   "Connection" "";
              proxy_pass http://budgetkey-app:4000;
            }
        }

        include /etc/nginx/servers.conf;
        include /etc/nginx/conf.d/*.conf;
    }

  default_server.conf: |
    server_name  next.obudget.org;

  servers.conf: |
    server {
      server_name socialpro.org.il www.socialpro.org.il;
      include "/etc/nginx/server-rules.conf";

      location / {
        #proxy_pass http://budgetkey-app:4000;
        
        default_type text/html;
        return 200 '<!DOCTYPE html><html lang="he" dir="rtl"><head><meta charset="utf-8"><title>מפתח לרכש החברתי | אתר בעדכון</title><style>body{margin:0;font-family:"Heebo",Arial,sans-serif;background:#fff;color:#fff}header{height:90px;display:flex;align-items:center;padding:0 40px}.notice-card{background:#192841;box-shadow:0 10px 10px #00000080;margin:40px auto;max-width:640px;padding:80px 40px;text-align:center;border-radius:8px}.notice-card h1{margin:0 0 24px 0;font-size:2rem;font-weight:700}.notice-card p{margin:0;font-size:1.25rem}</style></head><body dir="rtl"><header><img src="https://next.obudget.org/assets/common/img/soproc.svg" width="100"></header><section class="notice-card"><h1>מפתח לרכש החברתי</h1><p>האתר נמצא בעדכון ויחזור במהרה</p></section></body></html>';
      }
    }

    server {
      server_name data.obudget.org;
      return 301 https://redash.hasadna.org.il/;
    }

    server {
      server_name obudget.org www.obudget.org;
      rewrite ^ https://next.obudget.org/ permanent;
    }

    server {
      server_name socialmap.org.il www.socialmap.org.il;
      location / {
        proxy_pass http://socialmap-app-main-page:8000/;
      }
    }

     server {
       server_name dgp.obudget.org;
       location / {
           proxy_pass http://budgetkey-dgp-ui:8001;
       }
     }

    server {
      server_name pipelines.obudget.org;
      location / {
        proxy_pass http://budgetkey-data-pipelines:5000/;
      }
    }

    server {
      server_name data-input.obudget.org;
      location / {
        proxy_pass http://budgetkey-data-input:5000/;
      }
    }

  kibana.conf: |
    server {
        listen 80;
        server_name  kibana.obudget.org kibana2.obudget.org;
        client_max_body_size 50m;
        location / {
            proxy_pass http://kibana:5601;
            # auth_basic "Kibana";
            # auth_basic_user_file /etc/nginx/kibana.htpasswd;
        }
    }

  kibana.htpasswd: |
    elastic:$apr1$osnd5bKS$QCBIR1f6GiqNpN3b/hqzP.

  server-rules.conf: |
    location /search/ {
        proxy_http_version 1.1;
        proxy_set_header   "Connection" "";
        proxy_pass http://api-server;
    }

    location /get/ {
        proxy_http_version 1.1;
        proxy_set_header   "Connection" "";
        proxy_pass http://api-server;
    }

    location /api/ {
        proxy_http_version 1.1;
        proxy_set_header   "Connection" "";
        proxy_cache my_cache;
        proxy_pass http://slow-api-server;
    }

    location /lists {
        proxy_http_version 1.1;
        proxy_set_header   "Connection" "";
        proxy_pass http://api-server;
    }

    location /auth/ {
        proxy_http_version 1.1;
        proxy_set_header   "Connection" "";
        proxy_pass http://api-server;
    }

    location /datapackages {
       proxy_pass http://budgetkey-data-pipelines;
    }

    location /_fonts {
       root /var/;
       if ($request_filename ~ "^.+(eot|svg|ttf|otf|woff2|woff)$") {
           add_header "Access-Control-Allow-Origin" "*";
           add_header "Access-Control-Allow-Methods" "POST, GET, OPTIONS";
       }
       autoindex on;
       add_header Access-Control-Allow-Origin *;
    }

    location /govbuy/ {
        proxy_pass http://openprocure-app-main-page:8000;
    }

    location /income/ {
        proxy_pass http://budgetkey-app-source-of-money:8000;
    }

    location = /basic_status {
        stub_status;
    }

{{ end }}
