{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main_ext  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        '"$host" sn="$server_name" '
                        'rt=$request_time '
                        'ua="$upstream_addr" us="$upstream_status" '
                        'ut="$upstream_response_time" ul="$upstream_response_length" '
                        'cs=$upstream_cache_status' ;

        access_log  /var/log/nginx/access.log main_ext;

        proxy_cache_path /var/run/ levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout           65;
        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;

        gzip  on;

        server {
            listen 80 default_server;
            include /etc/nginx/default_server.conf;
            error_page 500 502 503 504 /500.html;
            location = /500.html {
                root /usr/share/nginx/errors;
                internal;
            }
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            include "/etc/nginx/server-rules.conf";

            location / {
              proxy_pass http://budgetkey-app:4000;
            }
        }

        include /etc/nginx/servers.conf;
        include /etc/nginx/conf.d/*.conf;
    }

  default_server.conf: |
    server_name  next.obudget.org;

  servers.conf: |
    server {
      server_name socialpro.org.il www.socialpro.org.il;
      include "/etc/nginx/server-rules.conf";

      location / {
        proxy_pass http://budgetkey-app:4000;
      }
    }

    server {
      server_name data.obudget.org;
      return 301 https://redash.hasadna.org.il/;
    }

    server {
      server_name obudget.org www.obudget.org;
      rewrite ^ https://next.obudget.org/ permanent;
    }

    server {
      server_name socialmap.org.il www.socialmap.org.il;
      location / {
        proxy_pass http://socialmap-app-main-page:8000/;
      }
    }

     server {
       server_name dgp.obudget.org;
       location / {
           proxy_pass http://budgetkey-dgp-ui:8001;
       }
     }

    server {
      server_name pipelines.obudget.org;
      location / {
        proxy_pass http://budgetkey-data-pipelines:5000/;
      }
    }

    server {
      server_name data-input.obudget.org;
      location / {
        proxy_pass http://budgetkey-data-input:5000/;
      }
    }

  kibana.conf: |
    server {
        listen 80;
        server_name  kibana.obudget.org kibana2.obudget.org;
        client_max_body_size 50m;
        location / {
            proxy_pass http://kibana:5601;
            auth_basic "Kibana";
            auth_basic_user_file /etc/nginx/kibana.htpasswd;
        }
    }

  kibana.htpasswd: |
    budgetkey:$apr1$osnd5bKS$QCBIR1f6GiqNpN3b/hqzP.

  server-rules.conf: |
    location /search/ {
        proxy_pass http://api:5000;
    }

    location /get/ {
        proxy_pass http://api:5000;
    }

    location /api/ {
        proxy_cache my_cache;
        proxy_pass http://api:5001;
    }

    location /list {
        proxy_pass http://budgetkey-list-manager:8000;
    }

    location /auth/ {
        proxy_pass http://api:5000;
    }

    location /datapackages {
       proxy_pass http://budgetkey-data-pipelines;
    }

    location /_fonts {
       root /var/;
       if ($request_filename ~ "^.+(eot|svg|ttf|otf|woff2|woff)$") {
           add_header "Access-Control-Allow-Origin" "*";
           add_header "Access-Control-Allow-Methods" "POST, GET, OPTIONS";
       }
       autoindex on;
       add_header Access-Control-Allow-Origin *;
    }

    location /govbuy/ {
        proxy_pass http://openprocure-app-main-page:8000;
    }

    location /dashboards/ {
        proxy_pass http://budgetkey-app-dashboards:8000;
    }

    location /income/ {
        proxy_pass http://budgetkey-app-source-of-money:8000;
    }

    location = /basic_status {
        stub_status;
    }

{{ end }}
