{{- if and .Values.enabled .Values.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  {{- if .Values.annotations }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
  {{ range .Values.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
  {{ end }}
{{- end }}