{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: '80'
    port: 80
  - name: '5601'
    port: 5601
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      {{ if .Values.global.persistentDataVolume.hostname }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.persistentDataVolume.hostname | quote }}
      {{ end }}
      containers:
      - name: nginx
        image: {{ .Values.image | default "budgetkey/open-budget-nginx-frontend:latest" | quote }}
        ports:
        - containerPort: 80
        - containerPort: 5601
        resources: {{ .Values.resources }}
        volumeMounts:
        - mountPath: /var/datapackages
          name: datapackages
        - mountPath: /var/_fonts
          name: fonts
      volumes:
      - name: datapackages
        {{ .Values.global.persistentDataVolume.type }}: {
          {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
            "path": "{{ .Values.global.persistentDataVolume.basePath }}/datapackages",
            "type": "DirectoryOrCreate"
          {{ end }}
        }
      - name: fonts
        {{ .Values.global.persistentDataVolume.type }}: {
          {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
            "path": "{{ .Values.global.persistentDataVolume.basePath }}/fonts",
            "type": "DirectoryOrCreate"
          {{ end }}
        }
{{ end }}
