{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: '80'
    port: 80
  - name: '5601'
    port: 5601
  selector:
    app: nginx
  {{ if .Values.enableLoadBalancer }}
  type: LoadBalancer
  {{ if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  {{ end }}
  {{ end }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      {{ if .Values.overrideServerRules }}
      annotations:
        # update the pod on nginx-conf changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{ end }}
    spec:
      {{ if .Values.global.persistentDataVolume.hostname }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.persistentDataVolume.hostname | quote }}
      {{ end }}
      containers:
      - name: nginx
        image: {{ .Values.image | default "budgetkey/open-budget-nginx-frontend:latest" | quote }}
        ports:
        - containerPort: 80
        - containerPort: 5601
        resources: {{ .Values.resources }}
        {{ if .Values.overrideStartupScript }}
        command:
        - sh
        - "-c"
        - |
          echo "NGINX STARTING"
          nginx -g "daemon off;"
        {{ end }}
        volumeMounts:
        - mountPath: /var/datapackages
          name: datapackages
        - mountPath: /var/_fonts
          name: fonts
        {{ if .Values.overrideServerRules }}
        - mountPath: /etc/nginx/server-rules.conf
          name: nginx-server-rules
          subPath: server-rules.conf
        {{ end }}
      volumes:
      - name: datapackages
        {{ .Values.global.persistentDataVolume.type }}: {
          {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
            "path": "{{ .Values.global.persistentDataVolume.basePath }}/datapackages",
            "type": "DirectoryOrCreate"
          {{ end }}
        }
      - name: fonts
        {{ .Values.global.persistentDataVolume.type }}: {
          {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
            "path": "{{ .Values.global.persistentDataVolume.basePath }}/fonts",
            "type": "DirectoryOrCreate"
          {{ end }}
        }
      {{ if .Values.overrideServerRules }}
      - name: nginx-server-rules
        configMap:
          name: nginx
      {{ end }}
{{ end }}
