{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emails
spec:
  selector:
    matchLabels:
      app: emails
  replicas: 1
  template:
    metadata:
      labels:
        app: emails
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: emails
        image: {{ .Values.image | default "budgetkey/budgetkey-emails:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        envFrom:
        {{ if .Values.secretName }}
        - secretRef:
            name: {{ .Values.secretName | quote }}
        {{ end }}
{{ end }}
