{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: api
        image: {{ .Values.image | default "budgetkey/budgetkey-api:latest" | quote }}
        ports:
        - containerPort: 5000
        resources: {{ .Values.resources }}
        env:
        - name: PORT
          value: "5000"
        - name: TIMEOUT
          value: "30"
        - name: SERVICES
          value: auth,es,lists
        - name: DATABASE_PRIVATE_URL
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DATABASE_PRIVATE_URL}}
        - name: ES_HOST
          value: elasticsearch-new
        - name: ES_PORT
          value: "9200"
        - name: INDEX_NAME
          value: {{ .Values.indexName | default "budgetkey" | quote }}
        - name: EXTERNAL_ADDRESS
          value: {{ .Values.global.serverName | default "next.obudget.org" | quote }}

        - name: GOOGLE_KEY
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: GOOGLE_KEY}}
        - name: GOOGLE_SECRET
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: GOOGLE_SECRET}}
        - name: PRIVATE_KEY
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: PRIVATE_KEY}}
        - name: PUBLIC_KEY
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: PUBLIC_KEY}}
        - name: SECRET_KEY
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: SECRET_KEY}}
        volumeMounts:
          - name: data
            mountPath: /var/run/budgetkey-api
            subPath: budgetkey-api
      - name: slow-api
        image: {{ .Values.image | default "budgetkey/budgetkey-api:latest" | quote }}
        ports:
        - containerPort: 5001
        resources: {{ .Values.resources }}
        env:
        - name: PORT
          value: "5001"
        - name: TIMEOUT
          value: "180"
        - name: SERVICES
          value: db,simpledb,es
        - name: DATABASE_READONLY_URL
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DATABASE_READONLY_URL}}
        - name: SECRET_KEY
          value: defunct
        - name: ES_HOST
          value: elasticsearch-new
        - name: ES_PORT
          value: "9200"
        - name: INDEX_NAME
          value: {{ .Values.indexName | default "budgetkey" | quote }}
        - name: EXTERNAL_ADDRESS
          value: {{ .Values.global.serverName | default "next.obudget.org" | quote }}

        volumeMounts:
          - name: data
            mountPath: /var/run/budgetkey-api
            subPath: budgetkey-api
      volumes:
      - name: data
        nfs:
          server: {{ .Values.nfsServer | quote }}
          path: {{ .Values.nfsPath | quote }}
{{ end }}
