{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: api
        image: {{ .Values.image | default "budgetkey/budgetkey-api:latest" | quote }}
        ports:
        - containerPort: 5000
        resources: {{ .Values.resources }}
        env:
        {{ if .Values.secretName }}
        - name: DATABASE_READONLY_URL
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DATABASE_READONLY_URL}}
        {{ else }}
        - name: DATABASE_READONLY_URL
          value: postgresql://budgetkey:123456@postgres/budgetkey
        {{ end }}
        - name: DATABASE_PRIVATE_URL
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DATABASE_PRIVATE_URL}}
        - name: ES_HOST
          value: elasticsearch-new
        - name: ES_PORT
          value: "9200"
        - name: INDEX_NAME
          value: {{ .Values.INDEX_NAME | default "budgetkey" | quote }}
        - name: EXTERNAL_ADDRESS
          value: {{ .Values.global.serverName | default "next.obudget.org" | quote }}
        envFrom:
        - configMapRef:
            name: auth
        {{ if .Values.secretName }}
        # override the values from configmap
        - secretRef:
            name: {{ .Values.secretName | quote }}
        {{ end }}

{{ end }}
