apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-dgp-ui
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: dgp-ui
  updatePolicy:
    updateMode: "Off"
