{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: socialmap-main-page
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: socialmap-main-page
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: socialmap
        image: {{ .Values.mainpageImage | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.mainpageResources }}
{{ end }}
