{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines
data:
  # AWS_ACCESS_KEY_ID:
  # AWS_SECRET_ACCESS_KEY:
  # DATABASE_URL: postgresql://*********@budgetkey-postgres/budgetkey
  DATAHUB_ENDPOINT: https://api.datahub.io
  DATAHUB_OWNER: budgetkey
  INDEX_NAME: budgetkey02
  # DATAHUB_OWNERID: *********
  # DATAHUB_TOKEN: *********
  # DPP_DB_ENGINE: postgresql://*********@budgetkey-postgres/budgetkey
  DATAFLOWS_ELASTICSEARCH: elasticsearch-new:9200
  # GITHUB_AUTH_TOKEN: *********
  S3_ENDPOINT_URL: https://ams3.digitaloceanspaces.com
{{ end }}
