{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines
spec:
  selector:
    matchLabels:
      app: pipelines
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pipelines
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: pipelines
        image: {{ .Values.image | default "budgetkey/budgetkey-data-pipelines:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        envFrom:
        - configMapRef:
            name: pipelines
        {{ if .Values.secretName }}
        # override the values from configmap
        - secretRef:
            name: {{ .Values.secretName | quote }}
        {{ end }}
        volumeMounts:
        - mountPath: /var/datapackages
          name: data
          subPath: budgetkey-persistent-data/datapackages
        - mountPath: /var/redis
          name: data
          subPath: budgetkey-persistent-data/redis
        - mountPath: /home/dpp/.ssh
          name: data
          subPath: budgetkey-persistent-data/.ssh
      - name: nginx
        image: nginx:alpine
        command:
        - sh
        - "-c"
          # ls -la /var/datapackages &&\
          # chmod -R 777 /var/datapackages &&\
        - |
          echo "HELLO WORLD!" &&\
          deluser nginx && addgroup -S nginx && adduser -D -S -u 1000 -h /var/cache/nginx -s /sbin/nologin -G nginx nginx &&\
          echo "NGINX STARTING" &&\
          nginx -g "daemon off;"
        ports:
        - containerPort: 80
        resources: {"requests": {"cpu": "12m", "memory": "194Mi"}, "limits": {"cpu": "78m", "memory": "1395Mi"}}
        volumeMounts:
        - name: pipelines-nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - mountPath: /var/datapackages
          name: data
          subPath: budgetkey-persistent-data/datapackages
        - name: escerts
          mountPath: /var/elasticsearch/certs
      volumes:
      - name: data
        {{ if .Values.gcePersistentDiskName }}
        gcePersistentDisk:
          pdName: {{ .Values.gcePersistentDiskName | quote }}
        {{ else if .Values.nfsServer }}
        nfs:
          server: {{ .Values.nfsServer | quote }}
          path: {{ .Values.nfsPath | quote }}
        {{ else }}
        emptyDir: {}
        {{ end }}
      - name: escerts
        nfs:
          server: {{ .Values.nfsServer | quote }}
          path: {{ .Values.nfsPathEsCerts | quote }}
      - name: pipelines-nginx-conf
        configMap:
          name: pipelines-nginx-conf
{{ end }}
