{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api-new
spec:
  selector:
    matchLabels:
      app: search-api-new
  replicas: 1
  template:
    metadata:
      labels:
        app: search-api-new
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: search-api-new
        image: {{ .Values.image | default "budgetkey/open-budget-search-api:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        env:
        - name: ES_HOST
          value: elasticsearch-new
        - name: ES_PORT
          value: "9200"
        - name: INDEX_NAME
          value: {{ .Values.INDEX_NAME | default "budgetkey" | quote }}
{{ end }}
