{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-main-page
spec:
  selector:
    matchLabels:
      app: app-main-page
  replicas: 1
  template:
    metadata:
      labels:
        app: app-main-page
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: app-main-page
        image: {{ .Values.image | default "budgetkey/budgetkey-app-main-page:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: themes
          mountPath: /themes
      volumes:
      - name: themes
        hostPath:
          path: /var/budgetkey-themes
          type: DirectoryOrCreate
{{ end }}
