global:
  namespace: budgetkey
  persistentDataVolume:
    type: hostPath
    basePath: /var/budgetkey-persistent-data
    hostname: gke-budgetkey-default-pool-bfb61637-qzv3
  serverName: next2.obudget.org

postgres:
  # gcloud --project=next-obudget-org compute disks create --size=100GB --zone=europe-west1-b budgetkey-postgres-data
  gcePersistentDiskName: budgetkey-postgres-data
  # kubectl create secret generic postgres --from-literal=POSTGRES_PASSWORD=
  secretName: postgres
  enableLoadBalancer: true
  # gcloud --project=next-obudget-org compute addresses create budgetkey-postgres --region=europe-west1
  # gcloud --project=next-obudget-org compute addresses describe budgetkey-postgres --region=europe-west1 | grep ^address:
  loadBalancerIP: 35.189.219.73

elasticsearch:
  # gcloud --project=next-obudget-org compute disks create --size=100GB --zone=europe-west1-b budgetkey-elasticsearch-data
  gcePersistentDiskName: budgetkey-elasticsearch-data
  resources: >
    {"requests": {"cpu": "1000m", "memory": "4Gi"}, "limits": {"cpu": "2500m", "memory": "6Gi"}}
  ES_JAVA_OPTS: "-Xms3g -Xmx3g"
  enableAntiAffinity: true

db-backup:
  createClusterRole: true
  # kubectl create secret generic db-backup --from-literal=S3_BUCKET= \
  #                                         --from-literal=S3_NAMESPACE= \
  #                                         --from-literal=AWS_ACCESS_KEY= \
  #                                         --from-literal=AWS_SECRET_KEY= \
  #                                         --from-literal=S3_HOST= \
  #                                         --from-literal=S3_HOST_BUCKET="
  secretName: db-backup

nginx:
  enableLoadBalancer: true
  # gcloud --project=next-obudget-org compute addresses create budgetkey-nginx --region=europe-west1
  # gcloud --project=next-obudget-org compute addresses describe budgetkey-nginx --region=europe-west1 | grep ^address:
  loadBalancerIP: 35.195.110.140
  image: orihoch/open-budget-nginx-frontend:changes-for-k8s-env
  overrideStartupScript: ls -la /var/datapackages && chmod 777 /var/datapackages && echo "NGINX STARTING" && nginx -g "daemon off;"
  enableAntiAffinity: true

data-api:
  # kubectl create secret generic data-api --from-literal=DATABASE_URL=postgresql://*****:*****@postgres/budgetkey \
  #                                        --from-literal=DB_USER=********* \
  #                                        --from-literal=DB_PWD=*********
  secretName: data-api

migration-from-docker-cloud:
  enabled: true
  datapackagesEnabled: true
  # kubectl create secret generic data-migration --from-file=private_key=/path/to/private/key \
  #                                              --from-literal=KEY_FILE= \
  #                                              --from-literal=SSH_USER= \
  #                                              --from-literal=SSH_HOST=
  dataMigrationSecretName: data-migration
