global:
  namespace: budgetkey
  # shared volume which requires all pods using it to be on the same node
  persistentDataVolume:
    type: hostPath
    basePath: /var/budgetkey-persistent-data
    hostname: gke-budgetkey-default-pool-bfb61637-qzv3
  serverName: next2.obudget.org

auth:
  # see the auth configmap for the required keys
  secretName: auth

data-api:
  # kubectl create secret generic data-api --from-literal=DATABASE_URL=postgresql://*****:*****@postgres/budgetkey
  secretName: data-api

db-backup:
  enabled: true
  createClusterRole: true
  # kubectl create secret generic db-backup --from-literal=S3_BUCKET= \
  #                                         --from-literal=S3_NAMESPACE= \
  #                                         --from-literal=AWS_ACCESS_KEY= \
  #                                         --from-literal=AWS_SECRET_KEY= \
  #                                         --from-literal=S3_HOST= \
  #                                         --from-literal=S3_HOST_BUCKET="
  secretName: db-backup

elasticsearch:
  # gcloud --project=next-obudget-org compute disks create --size=100GB --zone=europe-west1-b budgetkey-elasticsearch-data
  gcePersistentDiskName: budgetkey-elasticsearch-data
  resources: >
    {"requests": {"cpu": "1000m", "memory": "4Gi"}, "limits": {"cpu": "2500m", "memory": "6Gi"}}
  ES_JAVA_OPTS: "-Xms3g -Xmx3g"
  # prevents elasticsearch from scheduling on the same pod as pipelines and nginx
  enableAntiAffinity: true

list-manager:
  # kubectl create secret generic list-manager --from-literal=DATABASE_URL=
  secretName: list-manager

migration-from-docker-cloud:
  enabled: false
  datapackagesEnabled: false
  fontsEnabled: false
  redisEnabled: false
  sshEnabled: false
  setSshPermissionsEnabled: false
  setDatapackagesPermissionsEnabled: false
  setRedisPermissionsEnabled: false
  # persistent disks can only be mounted write from one node, stop the db/elasticsearch pods sbefore running the job
  # better to run it on the same node as the DB, so a re-mount of the persistent disk won't be needed
  dbEnabled: false
  dbPersistentDiskName: budgetkey-postgres-data
  dbNodeName: gke-budgetkey-default-pool-bfb61637-qzv3
  elasticsearchEnabled: false
  elasticsearchPersistentDiskName: budgetkey-elasticsearch-data
  elasticsearchNodeName: gke-budgetkey-default-pool-bfb61637-sczn
  # kubectl create secret generic data-migration --from-file=private_key=/path/to/private/key \
  #                                              --from-literal=KEY_FILE= \
  #                                              --from-literal=SSH_USER= \
  #                                              --from-literal=SSH_HOST=
  dataMigrationSecretName: data-migration
  # kubectl create secret generic elasticsearch-migration --from-file=private_key=/path/to/private/key \
  #                                                       --from-literal=KEY_FILE= \
  #                                                       --from-literal=SSH_USER= \
  #                                                       --from-literal=SSH_HOST=
  elasticsearchMigrationSecretName: elasticsearch-migration

nginx:
  enableLoadBalancer: true
  # gcloud --project=next-obudget-org compute addresses create budgetkey-nginx --region=europe-west1
  # gcloud --project=next-obudget-org compute addresses describe budgetkey-nginx --region=europe-west1 | grep ^address:
  loadBalancerIP: 35.195.110.140
  overrideStartupScript: ls -la /var/datapackages && chmod 777 /var/datapackages && echo "NGINX STARTING" && nginx -g "daemon off;"
  # prevents nginx from scheduling on the same node as elasticsearch
  enableAntiAffinity: true

pipelines:
  # see the pipelines configmap for the required keys
  secretName: pipelines
  resources: >
    {"requests": {"cpu": "800m", "memory": "2Gi"}, "limits": {"cpu": "1200m", "memory": "4Gi"}}
  # prevents pipelines from scheduling on the same node as elasticsearch
  enableAntiAffinity: true

postgres:
  # gcloud --project=next-obudget-org compute disks create --size=100GB --zone=europe-west1-b budgetkey-postgres-data
  gcePersistentDiskName: budgetkey-postgres-data
  # kubectl create secret generic postgres --from-literal=POSTGRES_PASSWORD=
  secretName: postgres
  enableLoadBalancer: true
  # gcloud --project=next-obudget-org compute addresses create budgetkey-postgres --region=europe-west1
  # gcloud --project=next-obudget-org compute addresses describe budgetkey-postgres --region=europe-west1 | grep ^address:
  loadBalancerIP: 35.189.219.73
