{{ if .Values.enabled }}
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: cluster-admin
spec:
  selector:
    matchLabels:
      name: cluster-admin
  template:
    metadata:
      labels:
        name: cluster-admin
    spec:
      containers:
      - name: sysctl-conf
        image: busybox:1.26.2
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144 && while true; do sleep 86400; done"]
        resources:
          requests:
            cpu: 1m
            memory: 5Mi
        securityContext:
          privileged: true
{{ end }}
