{{ if and .Values.enabled .Values.elasticsearchEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-migration
spec:
  template:
    metadata:
      name: elasticsearch-migration
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.elasticsearchNodeName | quote }}
      containers:
      - name: migration
        image: orihoch/budgetkey-k8s-utils-scp-data-migration:4
        env:
        - name: FROM_PATH
          value: /mnt/budgetkey-persistent-data/elasticsearch/
        - name: TO_PATH
          value: /var
        - name: KEY_FILE
          valueFrom: {secretKeyRef: {name: {{ .Values.elasticsearchMigrationSecretName | quote }}, key: KEY_FILE}}
        - name: SSH_USER
          valueFrom: {secretKeyRef: {name: {{ .Values.elasticsearchMigrationSecretName | quote }}, key: SSH_USER}}
        - name: SSH_HOST
          valueFrom: {secretKeyRef: {name: {{ .Values.elasticsearchMigrationSecretName | quote }}, key: SSH_HOST}}
        volumeMounts:
        - mountPath: /var/elasticsearch
          name: elasticsearch
        - mountPath: /secrets
          name: secrets
          readOnly: true
        resources: {"requests": {"cpu": "10m", "memory": "100Mi"}, "limits": {"cpu": "50m", "memory": "500Mi"}}
      restartPolicy: Never
      volumes:
      - name: elasticsearch
        gcePersistentDisk:
          pdName: {{ .Values.elasticsearchPersistentDiskName | quote }}
      - name: secrets
        secret:
          secretName: {{ .Values.elasticsearchMigrationSecretName | quote }}
{{ end }}
