{{ if and .Values.enabled .Values.setRedisPermissionsEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: set-redis-permissions
spec:
  template:
    metadata:
      name: set-redis-permissions
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.persistentDataVolume.hostname | quote }}
      containers:
      - name: ops
        image: alpine
        command:
        - sh
        - "-c"
        - chown -R 1000:1000 /var/redis
        volumeMounts:
        - mountPath: /var/redis
          name: redis
        resources: {"requests": {"cpu": "10m", "memory": "10Mi"}}
      restartPolicy: Never
      volumes:
      - name: redis
        {{ .Values.global.persistentDataVolume.type }}: {
          {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
            "path": "{{ .Values.global.persistentDataVolume.basePath }}/redis",
            "type": "DirectoryOrCreate"
          {{ end }}
        }
{{ end }}
