{{ if and .Values.enabled .Values.setSshPermissionsEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: set-ssh-permissions
spec:
  template:
    metadata:
      name: set-ssh-permissions
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.persistentDataVolume.hostname | quote }}
      containers:
      - name: ops
        image: alpine
        command:
        - sh
        - "-c"
        - chown 1000:1000 /var/.ssh/* && chmod 400 /var/.ssh/*
        volumeMounts:
        - mountPath: /var/.ssh
          name: ssh
        resources: {"requests": {"cpu": "10m", "memory": "10Mi"}}
      restartPolicy: Never
      volumes:
      - name: ssh
        {{ .Values.global.persistentDataVolume.type }}: {
          {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
            "path": "{{ .Values.global.persistentDataVolume.basePath }}/.ssh",
            "type": "DirectoryOrCreate"
          {{ end }}
        }
{{ end }}
