apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-app-about
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: app-about
  updatePolicy:
    updateMode: "Off"
