{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openprocure-app-main-page
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openprocure-app-main-page
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: openprocure
        image: {{ .Values.mainpageImage | default "budgetkey/openprocure-app-main-page:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.mainpageResources }}
        env:
          - name: BASE_PATH
            value: "/govbuy/"
        volumeMounts:
        - name: themes
          mountPath: /themes
      volumes:
      - name: themes
        hostPath:
          path: /var/budgetkey-themes
          type: DirectoryOrCreate
{{ end }}
