apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-openprocure-app-main-page
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: openprocure-app-main-page
