{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: {{ .Values.image | default "elastic/kibana:8.17.0" | quote }}
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "https://elasticsearch8:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "kibana_system"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: KIBANA_PASSWORD}}
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: "/usr/share/kibana/config/certs/ca/ca.crt"
        - name: SERVER_PUBLICBASEURL
          value: "https://kibana.obudget.org"
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: certs
          mountPath: /usr/share/kibana/config/certs
          readOnly: true
        - name: kibanadata
          mountPath: /usr/share/kibana/data
      volumes:
      - name: certs
        persistentVolumeClaim:
          claimName: elasticsearch-certs2
      - name: kibanadata
        persistentVolumeClaim:
          claimName: kibana-data2
{{ end }}
