{{ if .Values.enabled }}
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: themes
spec:
  selector:
    matchLabels:
      name: themes
  template:
    metadata:
      labels:
        name: themes
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: openprocure
        image: {{ .Values.openprocureImage | default "budgetkey/open-procure:latest" | quote }}
        command:
        - sh
        - "-c"
        - |
          cp -vrfL /theme.govbuy.json /themes/theme.govbuy.json &&\
          while true; do sleep 86400; done
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: themes
          mountPath: /themes
      - name: themes
        image: alpine
        command:
        - sh
        - "-c"
        - |
          cp -vrfL /configmap-themes/* /themes/ &&\
          while true; do sleep 86400; done
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: themes
          mountPath: /themes
        - name: configmap
          mountPath: /configmap-themes
      volumes:
      - name: themes
        hostPath:
          path: {{ .Values.global.themesHostPath | quote }}
          type: DirectoryOrCreate
      - name: configmap
        configMap:
          name: themes
{{ end }}
