{{ if .Values.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: themes
spec:
  selector:
    matchLabels:
      name: themes
  template:
    metadata:
      labels:
        name: themes
    spec:
      containers:
      - name: themes
        image: {{ .Values.themesImage | default "budgetkey/budgetkey-app-themes:latest" | quote }}
        command:
        - sh
        - "-c"
        - |
          cp -v prep/*.json /themes/ &&\
          while true; do sleep 86400; done
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: themes
          mountPath: /themes
      volumes:
      - name: themes
        hostPath:
          path: /var/budgetkey-themes
          type: DirectoryOrCreate
{{ end }}
